name: Build and Release JAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    # 1. 소스 코드 체크아웃
    - name: Checkout source code
      uses: actions/checkout@v3

    # 2. JDK 17 설정
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    # 3. Gradle 빌드
    - name: Build project
      run: ./gradlew bootJar

    # 4. 테스트 실행
    - name: Run tests
      run: ./gradlew test

    # 5. 빌드된 JAR 파일 업로드
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: spring-boot-jar
        path: build/libs/*.jar
