name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: write  # GitHub Pages 브랜치에 푸시 권한 추가

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'  # 사용할 JDK 배포판 지정 (temurin, zulu 등 중에서 선택)

    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew  # gradlew에 실행 권한 추가

    - name: Build project
      run: ./gradlew clean build

    - name: Run tests
      run: ./gradlew test

    # 4. SSH 키 설정
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # 5. 배포 디렉토리 생성 및 파일 업로드
    - name: Deploy JAR to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p ${{ secrets.APP_DIR }}"
        scp build/libs/*.jar ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.APP_DIR }}

    # 6. 서버에서 애플리케이션 실행
    - name: Restart application on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          pkill -f 'java -jar' || true
          nohup java -jar ${{ secrets.APP_DIR }}/HelloWorld-0.0.1-SNAPSHOT.jar > ${{ secrets.APP_DIR }}/app.log 2>&1 &
        EOF    

